services:
  - type: web
    name: smartlibrary-backend
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/SmartLibrarySE-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        value: postgresql://admin:zijcqvovFrGl0ShF2wrlgOMeMbywjGUH@dpg-d3dfpd3ipnbc73cambpg-a/smartlibrary_z6wv
      - key: DB_HOST
        value: dpg-d3dfpd3ipnbc73cambpg-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: smartlibrary_z6wv
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: zijcqvovFrGl0ShF2wrlgOMeMbywjGUH
      - key: JWT_SECRET
        value: mySecretKey123456789012345678901234567890
      - key: JWT_EXPIRATION
        value: 86400000
      - key: MISTRAL_API_KEY
        value: ql2AJYsj669bpSJGs2yuMVdGesqQ7qmL
      - key: MISTRAL_MODEL
        value: mistral-large-latest
      - key: MISTRAL_API_URL
        value: https://api.mistral.ai/v1/chat/completions
      - key: ADMIN_REGISTRATION_KEY
        value: admin
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-app.vercel.app
    plan: starter

